# Generated by Django 2.0.6 on 2018-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='balloon_drag_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Drag coefficient of balloon'),
        ),
        migrations.AddField(
            model_name='launch',
            name='balloon_dry_mass',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Mass of empty balloon (g)'),
        ),
        migrations.AddField(
            model_name='launch',
            name='design_burst_diam',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Design burst diameter of balloon (m)'),
        ),
        migrations.AddField(
            model_name='launch',
            name='nozzle_lift',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Nozzle lift (g)'),
        ),
        migrations.AddField(
            model_name='launch',
            name='parachute_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Area of parachute (m^2)'),
        ),
        migrations.AddField(
            model_name='launch',
            name='parachute_drag_c',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Drag coefficient of parachute'),
        ),
        migrations.AddField(
            model_name='launch',
            name='parachute_dry_mass',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Mass of parachute (g)'),
        ),
        migrations.AddField(
            model_name='launch',
            name='payload_dry_mass',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Mass off payload (g)'),
        ),
    ]
