# Generated by Django 2.1 on 2018-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180801_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
