# Generated by Django 3.0.2 on 2020-01-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20181009_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='slug',
            field=models.SlugField(default='matef'),
            preserve_default=False,
        ),
    ]
